# Generated by Django 4.2.5 on 2023-09-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
